version: '3'

services:
  nginx:
    build: ./
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    volumes:
      - ./nginx/var/www/html:/var/www/html
      - ./nginx/etc/nginx/conf:/etc/nginx/conf
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443

networks:
  default:
    external:
      name: ${NAME}